export const SITE_TITLE = 'Astro Portfolio Starter'
export const SITE_URL = 'https://astro-portfolio-starter.netlify.app/'
export const SITE_DESCRIPTION = 'Welcome to my personal website!'
export const PAGE_DESCRIPTION =
  'A simple portfolio theme for Astro powered by Tailwind CSS'
export const TWITTER = 'https://twitter.com/peoray_'
export const GITHUB = 'https://github.com/peoray/astro-portfolio-starter'
export const AUTHOR = 'Emmanuel Raymond'
export const IMAGE = '/images/photo.png'
export const IMAGE_ALT = 'Photo of an avatar'
